### ISSUE TITLE
AdvancedMobArena incompatible

### ISSUE THREAD

**Issue by Sikatsu** [xXKeyleXx/MyPet#1005]
They are able to bring their MyPets into the AdvancedMobArena.

https://www.spigotmc.org/resources/advancedmobarena.26838/

**Comment by xXKeyleXx** [comment]
There is not much I can do because this plugin has no freely available API. And even if I buy the plugin I would have to upload the plugin to my repo and this would be against his terms.

The other way around would be much easier:

Hook example: https://github.com/xXKeyleXx/MyPet/blob/master/modules/Plugin/src/main/java/de/Keyle/MyPet/util/hooks/MobArenaHook.java

How to register the hook:
MyPetApi.getPluginHookManager().registerHook(advancedMobArenaHook);
