### ISSUE TITLE
MyPet.command.store permission does not work

### ISSUE THREAD

**Issue by cuddylier** [xXKeyleXx/MyPet#1283]
# Bug report

* [x] I have checked other issues to make sure this is not a duplicate.

## Describe the bug

When a player has the MyPet.command.store permission, they still cannot use /petstore and get the message "You are not allowed to use this!".

## To Reproduce

_Steps to reproduce the behavior, please provide code snippets or a repository:_

1. Add the permission MyPet.command.store to a player
2. Type /petstore

## Expected behavior

Pet is stored.

## Actual behaviour

The error "You are not allowed to use this!" is shown.

## Additional context

> Please use the `/petadmin ticket` command and attach the generated `ticket.zip` from the MyPet folder to this issue.

I'll leave this off as it contains a lot of information that shouldn't be public, let me know if needed.

**Bukkit/Spigot/Bungee Build/Version:**
Paper 1.14.4 154

**MyPet Build/Version:**
3.5

**Permissions plugin:**
PermissionsEx 1.23.4

MyPet permissions used:

    - MyPet.command.release
    - MyPet.command.respawn
    - MyPet.command.name
    - MyPet.command.switch
    - MyPet.command.store
    - MyPet.command.trade.offer.*
    - MyPet.command.trade.receive.*
    - MyPet.skilltree.combat
    - MyPet.skilltree.utility
    - MyPet.skilltree.pvp
    - MyPet.skilltree.ride
    - MyPet.skilltree.farm
    - MyPet.petstorage.limit.10
    - MyPet.leash.*

**Comment by zerafox** [comment]
Try updating your MyPet to a newer build.

**Comment by wpmidia** [comment]
Sorry, but /petstore doesn't work yet... 
I used MyPet version 3.8 and 3.9 and I'm receiving the same error ... "You are not allowed to use this!"
All permissions were granted to players.

**Comment by MrGeennius** [comment]
Same bug here,
MyPet 3.9
PermissionsEx
MC 1.15.2

**Comment by zerafox** [comment]
> Same bug here,
> MyPet 3.9
> PermissionsEx
> MC 1.15.2

This is not a bug, you are missing a permission.

Commenting on a CLOSED ticket will not get you anywhere anyway.

**Comment by MrGeennius** [comment]
> .

So should i open a New bug report? tought you could not duplicate bug reports.
Im new at github, i don't see the solution in this post since "updating to the newer build" isn't a solution.
I also have all the permissions i guess i should've 
" - MyPet.command.store " and also " - MyPet.petstorage.limit.10 " i tried without storage limit too.
 how do you know we are missing a permission? and which one?

**Comment by zerafox** [comment]
Typically yes, if you have an issue, and there is no active tickets or a ticket with a solution for you. You create a new ticket.

Especially since you are NOT running the same as this ticket.
I'm blaming your permissions because "3.9" does not have a problem with the proper permissions in place.
So it is not a "Bug" but something wrong with your setup.

We're already here. So tell me more information with what's going on.
I need a Build Version, not just "3.9", there's a #XXX after that. What is it?
I assume your Server is SPIGOT and NOT some sort of random server version? You kind of left that out...
