### ISSUE TITLE
Quickly catch problems

### ISSUE THREAD

**Issue by GreenChennai** [xXKeyleXx/MyPet#1339]
# Bug report
Quickly catch problems

## Describe the bug
After opening Quick Capture, I saw purple items appearing on my head, attacking monsters and creatures, and the game flashed back. When I re-logged in to the game, I saw purple things on the monster's head and then suddenly flashed back
_A clear and concise description of what the bug is._

## To Reproduce

unknown Or as mentioned above

## Expected behavior

Game crash

## Actual behaviour

Game crash

## Additional context
https://sm.ms/image/4DiaF6Sqw1RrKx2
> Please use the `/petadmin ticket` command and attach the generated `ticket.zip` from the MyPet folder to this issue.
The player who provided me this question did not provide me with this file on his server
**Bukkit/Spigot/Bungee Build/Version:**
Paper1.12.2
**MyPet Build/Version:**
Mypet3.5-3.8Have trouble
 Mypet3.4No trouble
**What is the expected result?**
Game crash
**What happens instead of that?**
Game crash
**Error:**
```
Did not appear
```

**Comment by zerafox** [comment]
There should be an error of some sort that logs to your console when your game crashes.

What is "Quick Capture"?

I'm afraid I have 0 idea of what's going on this ticket, there's information all over the place and it's missing vital information to determine what is even happening.

All I can say at this point, is update the plugin further. Since apparently versions 3.5 to 3.8 all have, whatever this problem is... Try the 3.9 build.

**Comment by xXKeyleXx** [comment]
Do you use any mods?

**Comment by GreenChennai** [comment]
Do you use any mods?
yes，Use mods

**Comment by xXKeyleXx** [comment]
I just tried to reproduce it on my PC and it doesn't happen with vanilla MC 🤔 Maybe one of your mods is causing this.

**Comment by GreenChennai** [comment]
Ok i will ask the player for more info

**Comment by xXKeyleXx** [comment]
So any news on this?
