### ISSUE TITLE
1.16

### ISSUE THREAD

**Issue by xXKeyleXx** [xXKeyleXx/MyPet#1382]
- [x] compiles for 1.16
- [x] mobs
  - [x] Hoglins
  - [x] Piglins
  - [x] Striders
  - [x] Zoglins
- [x] add new mobs to Skilltree Creator
- [x] add Items to Item DB
- [x] Mark new armor/tooles/weapons as equipment

Maybe... Maybe not... Who knows

**Comment by mercurialmusic** [comment]
But hopefully!

**Comment by Baterka** [comment]
![356zn0](https://user-images.githubusercontent.com/3463591/85945112-d1114380-b93b-11ea-9b1a-330819cedb8c.png)

**Comment by iWisd0M5d** [comment]
If you can do it i really like this plugin :)

**Comment by Baterka** [comment]
Prioritize compilation please :_

**Comment by zerafox** [comment]
The amount of entitled impatience these days is absolutely astounding!
I wouldn't blame you Keyle for letting MyPet die at this point.

This is getting out of hand...

**Comment by mercurialmusic** [comment]
Showing support for the project =/= impatience.

**Comment by zerafox** [comment]
> Showing support for the project =/= impatience.


The amount of asking, questioning, persistent requests == impatience

1.16 has been asked about, requested, insisted upon, etc; so much over the course of just the past 2 days alone it's ridiculous.

There is "Support" and then there is "Failure to read/research already stated replies".
AND then there's the "Hurry up and make X the priority over Y" statements, which was removed from this ticket already.

**Comment by suningy** [comment]
Hope you can come out soon! Because I want to open a 1.16 server to use this plug-in

**Comment by Flap18** [comment]
> * [ ]  compiles for 1.16
> * [ ]  mobs
>   
>   * [ ]  Hoglins
>   * [ ]  Piglins
>   * [ ]  Striders
>   * [ ]  Zoglins
> * [x]  add new mobs to Skilltree Creator
> * [ ]  add Items to Item DB
> * [ ]  Mark new armor/tooles/weapons as equipment
> 
> Maybe... Maybe not... Who knows

Now? still same like 5 days ago

**Comment by Flap18** [comment]
please notices

**Comment by mercurialmusic** [comment]
Yeah, definitely see what you're talking about from some of these deleted comments. :( Just ew.

**Comment by digitalcrowd** [comment]
Hi xXKeyleXx!

I'm 45 years old. I'm an old guy. I supported your Premium Edition. Of all the plugins installed on my server that I have bene running for 8 years now, MyPet is the most requested plugin when the 1.16 update came through. Your plugin is amazing, awesome and players love it. Everyday they ask me, when will MyPet be updated? (as if I have any clue) Yes, I deal with entitlement issues all the time on my server, entitled to be staff, entitled to have things done their way or whatever. I don't make money on my server, I built it for my kids, but now that they don't really play it that much, I keep it up for everyone else, in spite of themselves. Imagine being able to login and go look at your builds from 7 years ago, if you were 13 and you're now 20, what a blast of memories. I don't run my server for the entitled, I run my server for those who love the game and love to create and love to play. I encourage you to continue developing MyPet, not because people are demanding it, but because YOUR plugin changes how the game is played in a good way, and that should be your motivation. If money was my only motivation, I would have shut down the server long ago. If it was about the jerks, entitled players, I would have shut it down. This is not about them, it's about you, and you as a person, and your legacy. :)

**Comment by FatherWh0** [comment]
Hello xXKeyleXx,

I too am an old guy (we'll leave it at that) running a Minecraft server since 2013. I just wanted a chance to tell you that I greatly appreciate your work and dedication that helps make our game more entertaining. Many of us adults like to get together late at night and make our pets fight each other. It's a bit of harmless fun we all enjoy. When a new player joins, one of the first things we do is offer them a pet. It's something everyone should get to experience.  I found MyPet while it was still Premium so my pets have the 'happy villager' particles. I really hope you don't let the kids and rude ppl get you down. You've done a great thing and you should be proud of the fun you've added to the game. Also, since your plugin is no longer premium, I feel you should add a donation link to your webpage. It would be nice for some of us to be able to show our appreciation by buying you a pizza. :)

Best wishes,
FatherWh0

**Comment by Baterka** [comment]
I would also donate some beers for faster update :P Players are hungry for this amazing plugin :D

**Comment by xXKeyleXx** [comment]
FYI a build for 1.16 is online!
