### ISSUE TITLE
Mypet Doesn't work with cauldron

### ISSUE THREAD

**Issue by GreenFoxx** [xXKeyleXx/MyPet#411]
Hello I have a cauldron server (a bukkit and forge server). I love the mypet plugin and it is one of my favorite plugins of them all. Unfortunally mypet doesn't work with cauldron. I would like for you to make a version of mypet that would work with cauldron. That way I can have a modded server but also have mypet. The problem with mypet on cauldron is that some of commands do not work such as /petcall. When ever I try the commands they give me a message in red that says: An Internal error occurred while attempting to preform this command. If you could please make a cauldron compatible version of mypet I would be very greatful. Thanks for your hard work ;)

**Comment by GreenFoxx** [comment]
could you please respond

**Comment by zerafox** [comment]
Developers can be quite busy, and while we know and love their plugins, they can't always be right ontop of things.
Keyle may be taking a break from Plugin Developing for the Holidays, or other reasons. Please be patient.

**Comment by GreenFoxx** [comment]
It doesn't have to be an alternate version all it has to be is for the next version of mypet (1.2.1) and all future versions to have cauldron compatibility.

**Comment by zerafox** [comment]
It doesn't work in Cauldron now, because the coding and checks are different in Cauldron than they are in Bukkit and Spigot.
I do not believe you can have complete compatibility with both Cauldron and these other server types without breaking something entirely, or a lot of work and a lot of bloat/code to do so.

I will leave this further to Keyle, as he is after all the Developer. Just be patient, he will respond when he has the time available.

**Comment by xXKeyleXx** [comment]
I was on vocation so I had no time to respond..... I may add Couldron support but not in the near future and I can not promise anything! Cauldron supports Bukkit plugins but MyPet is a CraftBukkit plugin that may or may not work on cauldron servers.

**Comment by GreenFoxx** [comment]
Ok I understand thanks for responding :)
