### ISSUE TITLE
Error with spigot 1.7.5 ¡HELP!

### ISSUE THREAD

**Issue by JavituRec** [xXKeyleXx/MyPet#425]
Hi I have a mistake, my server currently runs on version 1.7.5 of spigot. I leave the last log server. I hope to solve.
Log -> http://pastebin.com/Z5zuJSV7
Thanks, greetings.

**Comment by zerafox** [comment]
MyPet 1.1.9 is for 1.7.9-R0.2
You need to downgrade if you want MyPet to run on a 1.7.5 server.

**Comment by JavituRec** [comment]
Maven project MyPet (Bukkit 1.7.5)

MyPet Project Page | MyPet Wiki
	MyPet-1.1.9-SNAPSHOT.jar	855.19 KB	 view

http://build.keyle.de/job/MyPet%20%28Bukkit%201.7.5%29/

**Comment by JavituRec** [comment]
I tried also versions "mypet 1.1.7, 1.1.8, 1.1.9"

**Comment by zerafox** [comment]
Then you left out "Build Number", as well as a whole lot of other information when you opened this ticket.
Ideally, you want provide the Version of both your server and the plugin, as well as Build Numbers if they are Development Builds.

You also have to keep in mind that older versions of MyPet are written for CraftBukkit, not Bukkit or Spigot, so there may just simply be incompatibilities.
Also because it is an older version, quite a ways back even, that a fix or "update" is unlikely.

I'm also afraid outside of seeing that apparently a "version mismatch" is what's happening, I'm not so great with reading errorlogs, and personally my conclusion would simply be "MyPet is just incompatible with that version of Spigot." But I wouldn't know..

I'm sorry I'm not much help, if you've tried all the other versions written for 1.7.5, I wouldn't know what else to suggest to you, outside of switching to CraftBukkit.

But, perhaps Keyle can help you. You can always hold out hope that he'll be able to provide more insight than I can.

**Comment by xXKeyleXx** [comment]
@JavituRec I don't have a 1.7.5 version of craftbukkit/spigot so I can't compile the fix (b5e64edef007a573a6fe14a6b4747471bae30f11) for you :/
