### ISSUE TITLE
Player points support

### ISSUE THREAD

**Issue by Vidsify** [xXKeyleXx/MyPet#434]
Hi

Is it possible you could add support for PlayerPoints. On my network I have a points system and people get points by voting etc then can buy cosmetics in hubs/lobbies. I really would like the ability for them to buy pets with those points. I believe that PlayerPoints already has an Api which can be used. So if a pet cost 500 points and the player had 1000 they points will be subtracted, player gets pet forever, leaving them with 500 points.

Link to plugin: http://dev.bukkit.org/bukkit-plugins/playerpoints/

Thanks in advanced

**Comment by zerafox** [comment]
There are plenty of plugins out there that can run things based on commands. Other plugins such as BossShop for example works with a GUI that can be opened via command or sign click and connects with PlayerPoints (if I recall) which can subtract these points as the currency and run the command to give the player the pet, or the permission node to tame the pet.

With plenty of plugins out there with support for plugins such as PP, and their capability to run commands in exchange or otherwise there really isn't any need to add this sort of thing directly to plugins such as MyPet. :P
