### ISSUE TITLE
Default users cannot use /petchooseskilltree

### ISSUE THREAD

**Issue by fennectech** [xXKeyleXx/MyPet#463]
my default or trusted (non op) users cannot use /pcst or any of its aliases in the old or new way
it gives a "cannot do that now" thingy i can do it via /petadmin skilltree $user $skilltree
here is my ticket.zip ive used a workarround of automaticly selecting Combat via the YML

**Comment by zerafox** [comment]
Make sure that players have the correct permission node to use this command.

**Comment by fennectech** [comment]
what is the permission node   i havent seen any relating to skilltrees other than custom wich i have given the node using *
https://www.dropbox.com/sh/khllhkkbh9h9lgc/AADvcnXVZtqRcF6jbcagigFza?dl=0
thats my public folder with the ticket.zip

**Comment by fennectech** [comment]
also user can do all the other commands ive given them nodes for such as name and release

**Comment by fennectech** [comment]
btw automaticassignment as shown here doesnt seem to work
    AutomaticAssignment: Combat
    InheritAlreadyInheritedSkills: false
    ChooseOnce: true
    PreventLevellingWithout: true
    SwitchPenaltyFixed: 0.0
    SwitchPenaltyPercent: 5
    SwitchPenaltyAdmin: false
  Hooks:
unless im supposed to make it true and set the autoassignment somewhere else

**Comment by zerafox** [comment]
http://mypet.keyle.de/doku.php?id=en:permissions

You'll need to give the permissions for skill trees as well, as shown on the wiki. Though I believe this is only true if you've checked the box while creating the skilltree with the skilltree creator.
If you do not give players access to trees, there will be nothing to choose from.

If you are using GroupManager, the skilltree.* will not work, so you will need to list each tree...

I also believe that perhaps it is a configuration thing that OP's are able to over-ride. Double check your config file for any settings that may alter choosing alternate skill trees.

Also, it is best to Pastebin your files, rather than dropbox. No one particularly wants to download something that is easily pasted somewhere, as you never know what kind of viruses or other things you'll catch. ;P

Also Auto Assign does not work on Tree Name.
http://mypet.keyle.de/doku.php?id=en:configfile#automaticassignment

Auto Assigning already "chooses" once for the player, so if you want them to be able to change it at any point, set "ChooseOnce" to false. Or if you want them to choose on tame, but never change it again. Set Choose to True and Auto to False.

**Comment by fennectech** [comment]
i didnt create new skilltrees rahter modified the default one

**Comment by zerafox** [comment]
Well either way, the first skill tree in the list, is the "Auto" tree that will be applied. So if it's Combat, it will be combat. If it is Utility, it will be Utility.

**Comment by fennectech** [comment]
foxtail im on right now :)

On Tue, Apr 14, 2015 at 9:49 PM, Foxtail <notifications@github.com> wrote:

> Well either way, the first skill tree in the list, is the "Auto" tree that
> will be applied. So if it's Combat, it will be combat. If it is Utility, it
> will be Utility.
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/xXKeyleXx/MyPet/issues/463#issuecomment-93163416>.
>



-- 
Fennec
