### ISSUE TITLE
Again, owner lose pets!!!!

### ISSUE THREAD

**Issue by xion87** [xXKeyleXx/MyPet#490]
i updated my server from 1.8.3 to 1.8.7 and  all owner lose their pets... same issue of the last time... running bungeecord and spigot both in offline mode, this plugin start to piss me off...

**Comment by zerafox** [comment]
I don't remember Bungeecord support being re-added just yet, was it?

You're also not providing any error log reports or anything else, which is needed..

**Comment by xion87** [comment]
is the same erorr of this issue, https://github.com/xXKeyleXx/MyPet/issues/467

**Comment by zerafox** [comment]
So then I would expect it's because MyPet isn't built for 1.8.7 yet then. Bungeecord updated, did it?
I'm going to stand by the "mismatched versions" thing I've mentioned before, and you'll have to either wait for MyPet to update to 1.8.7 with everything else you're running, or downgrade again.

Since I didn't see anywhere you posted an errorlog of any kind on the last issue, I cannot begin to tell what kind of error that was exactly. Also since you are running now a different version of server, it isn't the exact same error. The plugins could be interacting differently due to your server's upgraded version...

**Comment by xXKeyleXx** [comment]
If this plugin pisses you off the don't use it. It was NEVER designed to work on server networks like BungeeCord and if Spigot/Bukkit has an update but the code revision doesn't change it's not my fault that it doesn't work. If you want to complain then do it the proper way and not in this bullshit "FIX YOUR SHIT" style. So do it in a proper way or fuck off!
