### ISSUE TITLE
Permissions for Endermites?

### ISSUE THREAD

**Issue by triarry** [xXKeyleXx/MyPet#505]
My players can tame rabbits and guardians, but no one except my admins can tame endermites. Is there a specific permission for these little guys?'

FYI I am running 1.8.7 and am using a 1.8.7 build, but the build server is down so I don't know which one.

**Comment by xXKeyleXx** [comment]
Well the permission should be "MyPet.user.leash.Endermite"

**Comment by triarry** [comment]
That didn't work. They already had MyPet.user.*, and I tried to give just the individual permission above, and it did not work.

**Comment by triarry** [comment]
Keep in mind, all other pets are leashed with no issue.

**Comment by triarry** [comment]
So, I just removed my pet and I was able to successfully tame an endermite. I have '*', so it is a permission typo or something?

**Comment by triarry** [comment]
I updated to the latest build and all SEEMS well, closing this ticket.

**Comment by triarry** [comment]
Keyle, I figured out exactly the problem. I made it so players can use any item (with mcMMO) towards their unarmed skill. The players are killing the endermites too quickly and causing them to die before they're before the threshold of health. If anyone else uses this feature in mcMMO, they will face the same issue. What do you recommend?

**Comment by triarry** [comment]
Realized I didn't reopen this.

**Comment by xXKeyleXx** [comment]
This shouldn't matter because the plugin calculates how much health is left after the hit percent and if that value is below 10% (negative values are smaller too) a pet is tamed. I thing mcMMO is messing with the damage values after MyPet checks for taming. So MyPet things a player did not enough damage to the endermite and mcMMO changes the values so that the endermites will die.
I will push a change that might fix this issue.
