### ISSUE TITLE
[REQUEST] backend request

### ISSUE THREAD

**Issue by Darkool** [xXKeyleXx/MyPet#519]
Hello Keyle, I would like to know what about mysql backend, It's coming?, Will be nice cross server with your pet or maybe add an option only to store (level, pet and name) to use it on lobbies,etc.
Thanks for your time.

Best regards.

**Comment by xXKeyleXx** [comment]
I would love to see that but I don't have the motivation to do that in my freetime because it's a hell lot of work and I don't play Minecraft myself very often. I had someone who offered to do that but I don't know the status or if he even started at all.

So I'm sorry but I don't thing it will happen :/

**Comment by Darkool** [comment]
Thanks for your reply, have you think about store json on mysql? Maybe it
can be more easy, but any way I understand your situation, thanks a lot.

**Comment by Darkool** [comment]
Maybe use redis can be a posibility ;)

**Comment by Phreag** [comment]
I have another Suggetstion for a easy to make backend:
 - Add an option to choose the storage location of the My.Pets file
 - make sure everything is written and loaded immediately from this file (no cache)

If that could be possible you could just choose a central place for the file and multiple Servers can use it. of Course it could create a lot off disk access sequences, but this should not be a problem if you are using a ssd.

@xXKeyleXx could that be possible to implement?

**Comment by xXKeyleXx** [comment]
That doesn't change anything because I read the file only once when the server starts. Everything else wouldn't make it easier than implementing a MySQL backend ;)

**Comment by Darkool** [comment]
ya, that's a problem, I think that the easier way it's using nosql db.
I remember that "ultimate bungee" stores his player's friends on json file on mysql, that's not a possibility?

**Comment by xXKeyleXx** [comment]
The best way would be to use a noSQL DB like MongoDB, this way I wouldn't have to mess arround with storing JSON/NBT/etc in a MySQL DB :P

**Comment by tara81** [comment]
I also would love bungee support.  Is this possible xxkeylexx ?

**Comment by tara81** [comment]
Okay I know you don't want to do this.. But please hear me out.

The pets that attack monsters is really cool, but let's face it, most monsters arent much of a challenge anyways.

So, this plugin really shines on servers with custom monsters (epicboss, mythicmobs .. etc)

The problem with custom monsters, is that you just can't have one server with it.  It is way too intensive and requires bungee, multiple servers to help with the load.

Your plugin doesnt support that.  So please, add some bungee database support, somehow.  Else players will have to level their pets on like 4 different servers to do different custom "quest lines"

Much <3 this plugin is truley awesome but does lack this one important feature, especially since it's so well suited for role playing servers with custom monsters.

**Comment by xXKeyleXx** [comment]
closed -> #527
