### ISSUE TITLE
Database Support (BungeeCord based servers)

### ISSUE THREAD

**Issue by Phreag** [xXKeyleXx/MyPet#527]
Hey, 

I am using the mypet Plugin on a Server which is based on bungeecord.
Right now mypet is only available on one server of the network, but i want to make it possible to use the pets even on another server.
Would it be possible to store Pets in a mysql database to allow multiple server to use the same pet database?

Would be really awesome...

**Comment by Phreag** [comment]
To make it really good it would bee good to save every change in pet data directly to mysql so it will be available immedialely on a different server.

For Spam reasons it should also be possible to disable the "XXX is now your active Mypet" message on login.

**Comment by Phreag** [comment]
Any Answer?

**Comment by xXKeyleXx** [comment]
see #519

**Comment by tara81** [comment]
Okay I know you don't want to do this.. But please hear me out.

The pets that attack monsters is really cool, but let's face it, most monsters arent much of a challenge anyways.

So, this plugin really shines on servers with custom monsters (epicboss, mythicmobs .. etc)

The problem with custom monsters, is that you just can't have one server with it.  It is way too intensive and requires bungee, multiple servers to help with the load.

Your plugin doesnt support that.  So please, add some bungee database support, somehow.  Else players will have to level their pets on like 4 different servers to do different custom "quest lines"

Much <3 this plugin is truley awesome but does lack this one important feature, especially since it's so well suited for role playing servers with custom monsters.

**Comment by xXKeyleXx** [comment]
I know it shines on servers with custom mobs because it was mainly written for that purpose :P but bungee wasn't a big thing when it was in active development so it was never intended to have big database backend. That makes it so hard and time consuming to rewrite this part.

It's not that I don't want to do this but rather the lack of a combination of time and motivation. I could do a kickstarter campain but I'm not really sure if anybody would even pay me to gain my motivation back xD

**Comment by tara81** [comment]
with all the downloads ur plugin has had and gets, i think u should just put it on spigot so everyone has to pay for updates , if the issue is money

**Comment by tara81** [comment]
heck I'd pay $10 for it to be bungee compatible :P Do realize though, that u cannot ride pets in the latest versions and that bug needs to be fixed also ;P

**Comment by tara81** [comment]
PS> How much motivation do u need? :P

**Comment by tara81** [comment]
Please respond <3

**Comment by zerafox** [comment]
Some kind of MySQL or database request has been made multiple times, and each time Keyle has explained that this is very time consuming and a lot of work.
Time of which is not currently available to do such a thing.

Discussing the database addition is much more than I expected at this point on the subject, so please have some patience if Keyle does not respond within 24 hours or so, Keyle is a very busy person with other things to do too.
Allow some time for life? :P

**Comment by tara81** [comment]
ah okay. I'm fairly certain a lot more admins would use this plugin if it supported bungee. And I know I would pay $10 for it, im sure some others would too!

**Comment by tara81** [comment]
zerafox" There are also equally large, if not larger requests that have been in place for a couple years now that have yet to see the light of day. "

Honestly , I believe bungee support is much more needed then other features people are requesting.

**Comment by zerafox** [comment]
Whether "needed" is the motive in question or not, you're "harassment" on the issue to press it relentlessly is very un-needed and if it were me, I'd probably put it on the bottom of my list due to the constant pestering on it.
Considering that there have been other requests that were accepted years ago now, and have been waited for just as long, from even a player/user standpoint it would be Fair to fullfill those requests before newer ones. Especially if it were from the Developer standpoint to keep the userbase happy.

Lets promise feature X and Y a long time ago, but first we're going to add these new requests A and B. Doesn't exactly look very good, now does it? And those requesting these features forever ago, having to wait even longer than they'd already had to a "squeaky wheel" user who wouldn't let up on a subject would be crushing and disappointing to the point where any Donation Support, probably even Usage Support will/may stop with MyPet.

And it's not very "kind" of you to down-look other requests simply because you REALLY want Bungee support for your server. Perhaps these other users don't consider bungee support to be very value-able at all, but their requests incredibly important for their setups?
"Needed" is opinion and position based, and you nor anyone else has any right to determine what is or isn't "more needed" than anything else. Only Keyle/The developer has that power.
So I'm going to ask again, that you let Keyle do their thing at their own pace and stop beating a dead horse.
The addition has already been accepted so far, don't turn it into a closed ticket and refused.

**Comment by tara81** [comment]
I dont think u understand that no bungee support really limits the use of this plugin on any RPG server.  RPG servers with more then a few bosses will lag if not bungee' due to limitations of Boss plugins.

**Comment by zerafox** [comment]
https://github.com/xXKeyleXx/MyPet/issues/527#issuecomment-152251804
Regardless of your ideal reasoning for pressing the issue, it is time to stop.
The Ticket is still open, and you should consider yourself lucky for that. Stop posting to other Tickets, stop pressing the issue every couple of hours. Just because you feel that Bungee is Very Important, doesn't mean it's going to happen, nor that it's going to happen any time soon for that matter.

I am locking this conversation, because it is getting out of Control. Keyle will do as they will with it from here.

**Comment by zerafox** [comment]
Already planned feature: #182
