### ISSUE TITLE
Disable caching and make path of My.Pets configurable

### ISSUE THREAD

**Issue by Phreag** [xXKeyleXx/MyPet#539]
I have tried to look into your code, but i dont know your plugin enough.

But it seems to make it possible to make the path for the my.pets configurable and save all changes immediately to it.

If you do a load on every player join (in a separated thread) and load his pet after reloading the file from disk it would be the same than using a database, but much less work.

Please, i beg you to make it multiserver compatible...
This will make your plugin very attractive for big Servers.

**Comment by tara81** [comment]
Okay I know you don't want to do this.. But please hear me out.

The pets that attack monsters is really cool, but let's face it, most monsters arent much of a challenge anyways.

So, this plugin really shines on servers with custom monsters (epicboss, mythicmobs .. etc)

The problem with custom monsters, is that you just can't have one server with it.  It is way too intensive and requires bungee, multiple servers to help with the load.

Your plugin doesnt support that.  So please, add some bungee database support, somehow.  Else players will have to level their pets on like 4 different servers to do different custom "quest lines"

Much <3 this plugin is truley awesome but does lack this one important feature, especially since it's so well suited for role playing servers with custom monsters.

**Comment by xXKeyleXx** [comment]
closed -> #527
