### ISSUE TITLE
Hello, read this please.

### ISSUE THREAD

**Issue by JugadorON** [xXKeyleXx/MyPet#580]
Hello, sorry for my bad english.

In a few weeks I open a network of servers. And for this reason I need myql in this plugin.

Please.

I take my time to configure this plugin. And I liked very much.

If you not put mysql, I can not use this plugin. Then I will have that use EchoPet, and I don't want to use EchoPet.

Please.

Do you can add mysql and upload an update in a few days? Thanks.

**Comment by Phreag** [comment]
I also already requested for that, but he is not willing to do something.
I use mypet on each server separated but it will be removed soon if he is not adding this?

@xXKeyleXx why are you not supporting your Plugin? if you would add Mysql Support it would make this Plugin usable for big servers. If it is about time or money, why dont you add it at spigot as a premium resource? Many People would pay for it because MyPet is just awesome!
Think about it - do you want to let it die?

**Comment by xXKeyleXx** [comment]
@JugadorON Don't open any other tickets! Do you think I closed them just for fun? There is an open issue already (#182) so continue there or I will ignore you at all.

@Phreag I never said that I'm not willing to add it but that I don't have the time and motivation. That's something completely different. Would you work X h/week for nothing? I think not! I know this would open a lot of possibilities for big servers and it would be awesome but it's a lot of work too. I can't add it as a premium resource because I don't meet the requirements (2 free plugins and 30 posts). So even if I wanted to, I can't. Anyway, if this plugin is so "awesome" why didn't you hit the donate button? 

Conclusion: If you don't pay for it you have to wait until I come around and find the time to add it.
