### ISSUE TITLE
Wither Eskeletons should not be Skeletons

### ISSUE THREAD

**Issue by ExtremoDuro** [xXKeyleXx/MyPet#587]
I created a skill tree for the skeletons, with the ranged ability. Wither Skeletons inherit it.

Could wither skeletons use their own skill tree?

**Comment by zerafox** [comment]
In the bukkit/spigot code, Wither Skeleton and Skeleton are the same thing.
I don't believe there is any differing code for them, outside of appearance
due to where they were spawned.

For example, if you take a Skeleton Spawn Egg into a Nether Fortress and
spawn something, you get a Wither Skeleton rather than a normal Skeleton.
