### ISSUE TITLE
MyPets teleportation

### ISSUE THREAD

**Issue by RoinujNosde** [xXKeyleXx/MyPet#599]
Hello,
New feature request:
An option in the config to disable/enable the auto-teleportation of pets. Also to cutomize the delay.

**Comment by zerafox** [comment]
You can already customize how far away a player should be from the pet
before it starts to follow.
Are you referring to the /petcall command?

**Comment by RoinujNosde** [comment]
I'm talkin' about:
Joseph has a pet named Joan. Joseph is in world Tantan.
Joseph teleports to world Brois. Joan is teleported to world Brois.

**Comment by zerafox** [comment]
That is the pet following the player, if you want to delay a teleport put
it on the player. o.O It's part of the pet's follow mechanic.

**Comment by zerafox** [comment]
It's the same thing as when a player teleports to either spawn or another
player. To put a delay on the pet's follow teleport, would also cause this
delay, and cause the pet to either be dismissed for the delay time-frame or
cause the pet to remain in the last location the player was.
I would imagine that this would cause chunks to remain loaded longer if no
one else was in the area, which isn't always a great idea. And would leave
the pet alone and vulnerable.

**Comment by RoinujNosde** [comment]
This delay thing is optional... Focus on the pet teleport. There is no way to make it manual?
If the player teleports, the pet goes away.

**Comment by RoinujNosde** [comment]
The player would have to call the pet again (/petcall)

**Comment by zerafox** [comment]
If you are using gateways or other functions to teleport your pets, I'm sure they offer a way to run commands for your players to have the pet dismissed when entering the gate/clicking a sign/etc; ?
Personally I feel it's just kind of silly to put a delay on the pet teleport or to dismiss the pet if the player teleports from one location to the other.

**Comment by RoinujNosde** [comment]
I use Essentials for teleportation, do you think Essentials can make players run cmds on teleport?
>  I feel it's just kind of silly to put a delay on the pet teleport 

Forget about the delay...
> to dismiss the pet if the player teleports from one location to the other.

Why you think it's silly?

**Comment by zerafox** [comment]
Last time I used Essentials, you could not use it to run commands for
players. No.
Most players when they talk about moving between worlds, they use gates,
and it seems to be that most gate plugins can run other commands on use
when a player walks through them. Which is why I mentioned applying the
dismissal command to one.
To force dismiss on a pet when teleporting can become more of a pain to the
player when moving from one place to another if they have to continue to
recall their pet each time. Especially when they've called it to start with
to be with them.
Let me ask you this, why do you want the pet to have a delay/dismissal on a
player's teleport?

**Comment by zerafox** [comment]
As an alternative, if you're really wanting players to have their pets dismissed when they teleport you can use this file that comes with your server: http://wiki.bukkit.org/Commands.yml
This allows you to "create commands" and in it you can create your own /TPA command and list both the essentials TPA and the MyPet dismiss command as well. That will accomplish your pet dismiss on teleport between players.
Do this again for when players use commands to teleport between worlds as well.

**Comment by RoinujNosde** [comment]
I use /warp and gates. If the player uses /warp, they will bypass the dismissal command...

> To force dismiss on a pet when teleporting can become more of a pain to the
player when moving from one place to another if they have to continue to
recall their pet each time. 

I think the player would get used to it.

> Let me ask you this, why do you want the pet to have a delay/dismissal on a
player's teleport?

Hard to explain.

Do you know that what i'm suggesting would be optional to server owners?

**Comment by xXKeyleXx** [comment]
I don't see a point in that. If they have access in both places the pet will stay until you send it away.

**Comment by RoinujNosde** [comment]
What if the player is trying to enter in a area where pets are not allowed?
Would not be annoying a pet in a skywars game?

**Comment by xXKeyleXx** [comment]
As long as the game is in another world this is not a problem, otherwise you have to use other plugins to block and send away the pet.

**Comment by RoinujNosde** [comment]
OK, this is the last time I make suggestions for MyPet.

**Comment by xXKeyleXx** [comment]
It's totally fine to "suggest" things but your suggestions were only good for you. Your first one would be debatable but only 1 in a thousand had a use for this one. Sure I could add all these little things but I don't want to add things that can easily done by other plugins or can only be used by one server just because it fits their needs. Another thing is that the plugin already had too many config options and I don't want to add more than I have to. I see so many comments about how difficult it is to set it up, I don't want to make it harder for them. I hope you understand that I can't please everyone. Thanks.

**Comment by RoinujNosde** [comment]
I understand.
But:
> OK, this is the last time I make suggestions for MyPet.
