### ISSUE TITLE
Changes in API

### ISSUE THREAD

**Issue by Rocologo** [xXKeyleXx/MyPet#680]
Hi Keyle

My Plugin MobHunting integrates to MyPet, but it looks like you have made a lot of changes in your API and I cant find the new names in the source code?

This is a piece of my code, I hope you can help?

`	private void onWolfKillMob(EntityDeathEvent event) {
		if (!MobHunting.isHuntEnabledInWorld(event.getEntity().getWorld())
				|| !(event.getEntity().getLastDamageCause() instanceof EntityDamageByEntityEvent))
			return;

		EntityDamageByEntityEvent dmg = (EntityDamageByEntityEvent) event
				.getEntity().getLastDamageCause();
		
		if (!(dmg.getDamager() instanceof MyPetEntity))
			return;

		MyPetEntity killer = (MyPetEntity) dmg.getDamager();

		if (killer.getPetType() != MyPetApi.Wolf)
			return;

		MobHunting.debug("A Wolf Killed a mob");`

I can't find "MyPetEntity" and "MyPetApi.Wolf" any more? I need to check if a killed entity is a MyPet or if the killer is a MyPet. How do I do this when I use your 1.3.2-SNAPSHOT repository?

**Comment by xXKeyleXx** [comment]
Yeah in order to make the plugin compatible with multiple versions of Minecraft I had to do a lot of refactoring. But I'm pretty satisfied with the result so I don't think the API will change a lot in the future.

`MyPetEntity` is now `MyPetBukkitEntity`
and
`MyPetType` was moved to `de.Keyle.MyPet.api.entity.MyPetType`

If you need any further help feel free to ask ;)

**Comment by Rocologo** [comment]
Thank you, That solved my issue. :-)
