### ISSUE TITLE
Error on console between MyPet and Survival Games

### ISSUE THREAD

**Issue by xkitox** [xXKeyleXx/MyPet#698]
[MyPet] Plugin MyPet v1.3.2 has failed to register events for class de.Keyle.MyPet.util.hooks.arenas.UltimateSurvivalGames because me/maker56/survivalgames/events/UserLobbyJoinedEvent does not exist.

This error comes up when I start my server up.  Not sure what it means or how to get rid of it.  Thanks!

**Comment by xXKeyleXx** [comment]
Which version of Ultimate Survival Games do you use?

**Comment by andris155** [comment]
http://dev.bukkit.org/bukkit-plugins/ultimatesurvivalgames/ - works perfectly
http://dev.bukkit.org/bukkit-plugins/survival-games/ - [MyPet] Plugin MyPet v1.3.2 has failed to register events for class de.Keyle.MyPet.util.hooks.arenas.UltimateSurvivalGames because me/maker56/survivalgames/events/UserLobbyJoinedEvent does not exist.

**Comment by xXKeyleXx** [comment]
Which one do you use?

**Comment by andris155** [comment]
I use: http://dev.bukkit.org/bukkit-plugins/ultimatesurvivalgames/

**Comment by xXKeyleXx** [comment]
I removed the support for the other one in 2.0.0 anyway so meh :P

**Comment by xkitox** [comment]
Oh I missed your message about my survival games plugin, I use https://www.spigotmc.org/resources/survival-games.17740/  Is this the one that no longer receives support? It's the only free up-to-date one I could find :D

**Comment by xXKeyleXx** [comment]
The one I removed the support for was abandoned on Bukkit dev. If the one you are using is up to date it shouldn't be a problem to support that.
