### ISSUE TITLE
A problem and a feature request.

### ISSUE THREAD

**Issue by Kronox12** [xXKeyleXx/MyPet#824]
1. The problem: Whenever I leash a Villager and then release it, it disappears instantly.
This only occurs when I leash it, it doesn't happen with the /petadmin create command.
2. Feature request: Make a list of available items for pets's food, so that we can translate them too. I haven't found anything about translating food items in the config/locale files.

MyPet Premium 2.1.8, MC 1.10

**Comment by zerafox** [comment]
Food items can be set within the config file, there isn't a need to list
them elsewhere by the Developer. You can change them as you like, and they
should auto-translate I'd think with the client's set language as well.
Since after all, this config file is just saying "this item can be fed to
the pet for Hunger/Health points."

**Comment by Kronox12** [comment]
Sadly, for me it doesn't translate the items's names regardless of the client's language.

**Comment by xXKeyleXx** [comment]
Please open one ticket for each point next time.

I will look into the villager problem. 

Sadly the Minecraft server only has the English translation included. So there is not much I can do without translating all item names. But I could allow the translation via custom translations or show the custom name if the item has one.

**Comment by Kronox12** [comment]
Allright :)
