### ISSUE TITLE
Pets are invisible

### ISSUE THREAD

**Issue by kyakou** [xXKeyleXx/MyPet#964]
Please provide the following info.

**Bukkit/Spigot/Bungee Build/Version:** Spigot 1.11

**MyPet Build/Version:** 2.2.9

**Do you use the premium version? (this wont change anything for you)** I do not.

**What is the expected result?** When taming pets or creating pets with the admin commands, all pets are supposed to be visible and working correctly.

**What happens instead of that?** Tamed pets are invisible and do not show up in Gamemode three. Even when calling the pet, it is still invisible. Entity count does not change.

**Error:**

No errors in console at all. Doesn't even say MyPets was enabled, even though the commands work in game.

[MyPet.log.txt](https://github.com/xXKeyleXx/MyPet/files/728456/MyPet.log.txt)

**Comment by xXKeyleXx** [comment]
Does this always happen or just sometimes?

**Comment by kyakou** [comment]
It always happens.

**Comment by xXKeyleXx** [comment]
Could you please ZIP the whole server (if possible with map) and upload it for me so I can figure out why this happens.

**Comment by kyakou** [comment]
Sorry about the late reply- I have been busy with studies. I can't zip the whole server, as it is to big and it would take a pretty long time. Is it okay if I tell you what plugins we have? We're currently using a resource pack to, but it only adds textures by durability and doesn't change anything else. Even before the resource pack, this was still happening.
![2017-01-30_20 46 00](https://cloud.githubusercontent.com/assets/25336237/22452607/363bbcfc-e72d-11e6-8828-6086fd3264de.png)

**Comment by xXKeyleXx** [comment]
I asked because you said it always happens on your server. With a constellation where I can reproduce it I would be able to fix it in a few hours because this error never happens on my small testserver. Could you at least upload your plugins folder? It shouldn't be that big and might contain all I need to fix the problem. If you don't want to upload it here to the public you can upload it somewhere safe and send me the link on Spigot or per email.

**Comment by xXKeyleXx** [comment]
Please try the latest dev build: https://mypet-plugin.de/download
